name: uban267
on: [push, pull_request]
jobs:
  build:
    name: history1
    runs-on: ubuntu-latest
    steps:
      - uses: gass
        with:
          go-version: 1.13
      - uses: actions/checkout@v1
      - name: Test
        run: make test
